apiVersion: 1
datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: TimescaleDB
    uid: tsdb
    type: grafana-postgresql-datasource
    url: timescaledb:5432
    user: fleet
    secureJsonData: { password: fleet }
    jsonData: { database: telemetry, sslmode: disable, timescaledb: true, postgresVersion: 1600 }
